name: Deploy Flask

on:
  push:
    branches: [ "main" ]  # Se ejecuta cada vez que hagas push a main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar el repo
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Configurar variable de entorno
        run: echo "HF_API_TOKEN=${{ secrets.HF_API_TOKEN }}" >> $GITHUB_ENV

      - name: Ejecutar Flask
        run: python app.py
